FlOpEDT/TTapp/urls.py
from django.conf.urls import url, include
from django.urls import path

import TTapp.views

app_name = "TTapp"

urlpatterns = [
    path('side_panel/<int:year>/<int:week>',
         TTapp.views.available_work_copies,
         name="available_work_copies"),
    path('check_swap/<int:year>/<int:week>/<int:work_copy>',
         TTapp.views.check_swap,
         name="check_swap"),
    path('swap/<int:year>/<int:week>/<int:work_copy>',
         TTapp.views.swap,
         name="swap"),
    path('delete_work_copy/<int:year>/<int:week>/<int:work_copy>',
         TTapp.views.delete_work_copy,
         name="delete_work_copy"),
    path('duplicate_work_copy/<int:year>/<int:week>/<int:work_copy>',
         TTapp.views.duplicate_work_copy,
         name="duplicate_work_copy"),
    path('delete_all_unused_work_copies/<int:year>/<int:week>',
         TTapp.views.delete_all_unused_work_copies,
         name="delete_all_unused_work_copies"),
    path('reassign_rooms/<int:year>/<int:week>/<int:work_copy>',
         TTapp.views.reassign_rooms,
         name="reassign_rooms"),
    path('fetch_group_lunch',
         TTapp.views.fetch_group_lunch,
         name="fetch_group_lunch"),
]

FlOpEDT/api/base/rooms/urls.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
#
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.
from rest_framework import routers

from api.base.rooms import views

routerRooms = routers.SimpleRouter()

routerRooms.register(r'types', views.RoomTypesViewSet)
routerRooms.register(r'names', views.RoomNameViewSet)
routerRooms.register(r'room', views.RoomViewSet)
routerRooms.register(r'all', views.RoomAllViewSet, basename='all')
routerRooms.register(r'sorts', views.RoomSortsViewSet)

FlOpEDT/api/base/urls.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
#
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.
from rest_framework import routers

from api.base import views

routerBase = routers.SimpleRouter()

# routerBase.register(r'studentspreferences', views.StudentPreferencesViewSet, basename="students")
# routerBase.register(r'groupspreferences', views.GroupPreferencesViewSet)

# routerBase.register(r'departments', views.DepartmentViewSet)
routerBase.register(r'trainingprogram/name', views.TrainingProgrammeNameViewSet, basename='trainingprogramme-name')
# routerBase.register(r'trainingprogram', views.TrainingProgrammeViewSet)
# routerBase.register(r'holidays', views.HolidaysViewSet)
# routerBase.register(r'traininghalfdays', views.TrainingHalfDaysViewSet)
# routerBase.register(r'periods', views.PeriodsViewSet)
# routerBase.register(r'timesettings', views.TimeGeneralSettingsViewSet)
# routerBase.register(r'edtversions', views.EdtVersionsViewSet)
# routerBase.register(r'coursemodifications', views.CourseModificationsViewSet)
# routerBase.register(r'tutorcosts', views.TutorCostsViewSet)
# routerBase.register(r'groupcosts', views.GroupCostsViewSet)
# routerBase.register(r'CourseStartTimeFilter', views.GroupFreeHalfDaysViewSet)
# routerBase.register(r'dependencies', views.DependenciesViewSet)
# routerBase.register(r'coursesstarttimeconstraints', views.CourseStartTimeConstraintsViewSet)
# routerBase.register(r'regens', views.RegensViewSet)
# routerBase.register(r'login', views.LoginView, basename="login")
# routerBase.register(r'logout', views.LogoutView, basename="logout")

FlOpEDT/api/urls.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
# 
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.

from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.views.generic import TemplateView
from drf_yasg import openapi
# from rest_framework_swagger.renderers import SwaggerUIRenderer, OpenAPIRenderer
from drf_yasg.views import get_schema_view
from rest_framework import routers, permissions
from rest_framework.authtoken.views import obtain_auth_token

import api.base.views as views_base
import api.fetch.views as views_fetch
from api import views
from api.TTapp.urls import routerTTapp
from api.base.urls import routerBase
from api.base.rooms.urls import routerRooms
from api.base.groups.urls import routerGroups
from api.base.courses.urls import routerCourses
from api.fetch.urls import routerFetch
from api.people.urls import routerPeople
from api.preferences.urls import routerPreferences
from api.myflop.urls import routerMyFlop

#####################################
# URLS based on django applications #
#####################################

app_name = "api"

routerDisplayweb = routers.SimpleRouter()

routerDisplayweb.register(r'breakingnews', views.BreakingNewsViewSet)
routerDisplayweb.register(r'moduledisplays', views.ModuleDisplaysViewSet)
routerDisplayweb.register(r'trainingprogrammedisplays', views.TrainingProgrammeDisplaysViewSet)
routerDisplayweb.register(r'groupdisplays', views.GroupDisplaysViewSet)


######################
# User friendly URLS #
######################

routerExtra = routers.SimpleRouter()

routerExtra.register('bknews', views_fetch.BKNewsViewSet, basename="bknews")
routerExtra.register('quote/random', views.RandomQuoteViewSet, basename="random-quote")
routerExtra.register('quote', views.QuoteViewSet)
routerExtra.register('week-infos', views.WeekInfoViewSet, basename="week-infos")

################
# SWAGGER VIEW #
################
schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    url(r'^$', views_base.LoginView.as_view()),
    url(r'^logout/$', views_base.LogoutView.as_view()),
    url(r'^backoffice/$', login_required(TemplateView.as_view(template_name='logout.html'))),
    path('base/', include((routerBase.urls, 'api'), namespace='base')),
    path('user/', include(routerPeople.urls)),
    path('display/', include(routerDisplayweb.urls)),
    path('ttapp/', include((routerTTapp.urls, 'api'), namespace='ttapp')),
    path('fetch/',
         include((routerFetch.urls, 'api'), namespace='fetch')),
    path('rest-auth/', include('rest_auth.urls')),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
    url('doc/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('preferences/', include(routerPreferences.urls)),
    path('rooms/',
         include((routerRooms.urls, 'api'), namespace = 'rooms')),
    path('courses/',
         include((routerCourses.urls, 'api'), namespace = 'course')),
    path('groups/',
         include((routerGroups.urls, 'api'), namespace = 'groups')),
    path('extra/',
         include((routerExtra.urls, 'api'), namespace='extra')),
    path('myflop/',
         include((routerMyFlop.urls, 'api'), namespace='myflop')),
]

FlOpEDT/base/urls.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
# 
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.

from django.conf.urls import url, include
from django.urls import path, re_path
from . import views
from . import statistics
from django.views.generic import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

app_name="base"

urlpatterns = [
    # favicon
    # ----------------------------
    url(views.fav_regexp,
        views.favicon,
        name="favicon"),

    # directly reachable by users
    # ----------------------------
    re_path(r'room-preference/(?P<tutor>\w{2,8})?', views.room_preference, name='room-pref'),
    re_path(r'visio-preference/(?P<tutor>\w{1,8})?(/?P<id>\d{1,8})?',
            views.visio_preference,
            name='visio-pref'),

    url(r'^preferences$', views.preferences, name="preferences"),
    url(r'^semaine-type$', views.stype, name="stype"),
    url(r'^aide$', views.aide, name="aide"),
    url(r'^decale$', views.decale, name="decale"),    
    url(r'^contact/(?P<tutor>\w{2,8})?$', views.contact, name="contact"),
    url(r'^module_description(/(?P<module>\w{1,8}))?$', views.module_description, name="module_description"),
    url(r'^((?P<year>\d{4}))?(/(?P<week>\d{1,2}))?$', views.edt, name="edt"),
    url(r'^tv(/(?P<year>\d+))?(/(?P<week>\d+))?$', views.edt_light, name="edt_light"),
    url(r'^modules$', views.all_modules_with_desc, name="modules"),
    #Send Email to teacher when student want modify schedule
    url(r'^email-modif$', views.send_email_proposal, name='email-proposal'),

    # exchanges with the db via django
    # ---------------------------------

    # from db to screen
    path('fetch_user_default_week/<str:username>', views.fetch_user_default_week, name="fetch_user_dweek"),
    path('fetch_course_default_week/<str:train_prog>/<str:course_type>', views.fetch_course_default_week, name="fetch_course_dweek"),
    path('fetch_room_default_week/<str:room>', views.fetch_room_default_week, name="fetch_room_dweek"),
    url(r'^fetch_decale$', views.fetch_decale, name="fetch_decale"),
    url(r'^fetch_bknews/(?P<year>\d+)/(?P<week>\d+)$', views.fetch_bknews, name="fetch_bknews"),
    url(r'^fetch_groups$', views.fetch_groups, name="fetch_groups"),    
    url(r'^fetch_rooms$', views.fetch_rooms, name="fetch_rooms"),    
    url(r'^fetch_flat_rooms$', views.fetch_flat_rooms, name="fetch_flat_rooms"),    
    url(r'^fetch_constraints$', views.fetch_constraints, name="fetch_constraints"),
    path('fetch_course_types', views.fetch_course_types, name="fetch_course_types"),
    path('fetch_training_programmes', views.fetch_training_programmes, name="fetch_training_programmes"),
    url(r'^fetch_unavailable_rooms/(?P<year>\d+)/(?P<week>\d+)$', views.fetch_unavailable_rooms, name="fetch_unavailable_rooms"),
    url(r'^fetch_all_tutors/$', views.fetch_all_tutors, name="fetch_all_tutors"),
    url(r'^fetch_all_versions/$', views.fetch_all_versions, name="fetch_all_versions"),
    path('fetch_departments', views.fetch_departments, name="fetch_departments"),
    path('fetch_tutor_courses/<int:year>/<int:week>/<str:tutor>', views.fetch_tutor_courses, name="fetch_tutor_courses"),
    path('fetch_extra_sched/<int:year>/<int:week>', views.fetch_extra_sched, name="fetch_extra_sched"),
    path('fetch_shared_rooms/<int:year>/<int:week>', views.fetch_shared_rooms, name="fetch_shared_rooms"),
    path('fetch_perfect_day/<str:username>', views.fetch_perfect_day, name="fetch_perfect_day"),
    path('fetch_user_notifications_pref/<str:username>', views.fetch_user_notifications_pref, name="fetch_user_notifications_pref"),
    url(r'^fetch_module/(?P<year>\d+)/(?P<week>\d+)$', views.fetch_module, name="fetch_module"),
    url(r'^fetch_tutors/(?P<year>\d+)/(?P<week>\d+)$', views.fetch_tutor, name="fetch_tutor"),
    url(r'^fetch_all_modules_with_desc$', views.fetch_all_modules_with_desc, name="fetch_all_modules_with_desc"),
    url(r'^fetch_all_dispos$', views.fetch_all_dispos, name="fetch_all_dispos"),
    path('fetch_group_preferred_links',
         views.fetch_group_preferred_links,
         name='fetch_group_preferred_links'),

    # statistics
    # ---------------------------------
    path('statistics/', include([
        path('', statistics.index, name="statistics"),
        path('rooms/', statistics.fetch_room_activity, name="room_activity"),
        path('tutors/', statistics.fetch_tutor_hours, name="tutor_hours"),
        path('groups/', statistics.fetch_group_hours, name="group_hours"),
    ])),

    # from screen to db
    path('change_edt', views.edt_changes, name="edt_changes"),
    path('change_user_pref/<int:year>/<int:week>/<str:username>',
         views.user_preferences_changes,
         name="user_pref_changes"),
    path('change_course_pref/<int:year>/<int:week>/<str:train_prog>/<str:course_type>', views.course_preferences_changes, name="course_pref_changes"),
    path('change_room_pref/<int:year>/<int:week>/<str:room>',
         views.room_preferences_changes,
         name="room_pref_changes"),
    path('change_decale', views.decale_changes, name="decale_changes"),
    path('change_perfect_day/<str:username>',
         views.user_perfect_day_changes,
         name="user_perfect_day_changes"),
    path('change_user_notifications_pref/<str:username>',
         views.user_notifications_pref_changes,
         name="user_notifications_pref_changes"),
    path(r'change_room_pref_per_tutor/<str:tutor>',
         views.room_preferences_changes_per_tutor,
         name='room_pref_changes_per_tutor'),

    # predefined
    # ------------
]

# https://pypi.python.org/pypi/django-live-log
# https://github.com/abdullatheef/django_live_log

FlOpEDT/easter_egg/urls.py
from django.urls import path
import easter_egg.views as views

app_name = "easter_egg"

urlpatterns = [
    path('', views.start_game, name="start_game"),
    path('fetch_leaderboard', views.fetch_leaderboard, name="fetch_leaderboard"),
    path('set_score', views.set_score, name="set_score"),
]

FlOpEDT/ics/urls.py
from django.urls import path
from ics.feeds import TutorEventFeed, RoomEventFeed, StructuralGroupEventFeed, TransversalGroupEventFeed, RegenFeed

from ics import views

app_name = 'ics'

urlpatterns = [
    path(r'', views.index, name="index"),
    path(r'tutor/<int:tutor_id>.ics', TutorEventFeed(), name="tutor"),
    path(r'room/<int:room_id>.ics', RoomEventFeed(), name="room"),
    path(r'structural_group/<int:group_id>.ics', StructuralGroupEventFeed(), name="structural_group"),
    path(r'transversal_group/<int:group_id>.ics', TransversalGroupEventFeed(), name="transversal_group"),
    path(r'regen/<int:dep_id>.ics', RegenFeed(), name="regen"),
]

FlOpEDT/base/templates/base/contact.html
<!-- This file is part of the FlOpEDT/FlOpScheduler project.               -->
<!-- Copyright (c) 2017                                                    -->
<!-- Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.           -->
<!--                                                                       -->
<!-- This program is free software: you can redistribute it and/or modify  -->
<!-- it under the terms of the GNU Affero General Public License as        -->
<!-- published by the Free Software Foundation, either version 3 of the    -->
<!-- License, or (at your option) any later version.                       -->
<!--                                                                       -->
<!-- This program is distributed in the hope that it will be useful, but   -->
<!-- WITHOUT ANY WARRANTY; without even the implied warranty of            -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU      -->
<!-- Affero General Public License for more details.                       -->
<!--                                                                       -->
<!-- You should have received a copy of the GNU Affero General Public      -->
<!-- License along with this program. If not, see                          -->
<!-- <http://www.gnu.org/licenses/>.                                       -->
<!--                                                                       -->
<!-- You can be released from the requirements of the license by purchasing -->
<!-- a commercial license. Buying such a license is mandatory as soon as   -->
<!-- you develop activities involving the FlOpEDT/FlOpScheduler software   -->
<!-- without disclosing the source code of your own applications.          -->

{% extends "base.html" %}
{% load i18n %}
{% block title %} EDT {% endblock %}
{% block content %}
<font color="black">
<form method="post" novalidate>
  {% csrf_token %}
  <table cellpadding="10">
    {{ form }}
  </table>
  <button type="submit">{%trans "Send" %}</button>
  <div> {{ ack }} </div>
  <div> <br/><br/> </div>
</form>
</font>
{% endblock %}

FlOpEDT/base/templates/base/departments.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}

{% if departments %}
<script type="text/javascript">
function goTo(url){
    location.href = url;
};
</script>
<div class="dept_container">
    <div class="dept_list">
        <p>
            {% trans "Please choose your department : " %}
        </p>
        <ul>
            {% for department in departments %}
            <li onclick="goTo('{% url "base:edt" department.abbrev %}');">{{ department.name }}</li>
            {% endfor %}
        </ul>
    </div>
</div>
{% else %}
    <p>No departments are available.</p>
{% endif %}

{% endblock %}

FlOpEDT/base/templates/base/edt-base.html
<!-- This file is part of the FlOpEDT/FlOpScheduler project.               -->
<!-- Copyright (c) 2017                                                    -->
<!-- Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.           -->
<!--                                                                       -->
<!-- This program is free software: you can redistribute it and/or modify  -->
<!-- it under the terms of the GNU Affero General Public License as        -->
<!-- published by the Free Software Foundation, either version 3 of the    -->
<!-- License, or (at your option) any later version.                       -->
<!--                                                                       -->
<!-- This program is distributed in the hope that it will be useful, but   -->
<!-- WITHOUT ANY WARRANTY; without even the implied warranty of            -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU      -->
<!-- Affero General Public License for more details.                       -->
<!--                                                                       -->
<!-- You should have received a copy of the GNU Affero General Public      -->
<!-- License along with this program. If not, see                          -->
<!-- <http://www.gnu.org/licenses/>.                                       -->
<!--                                                                       -->
<!-- You can be released from the requirements of the license by purchasing -->
<!-- a commercial license. Buying such a license is mandatory as soon as   -->
<!-- you develop activities involving the FlOpEDT/FlOpScheduler software   -->
<!-- without disclosing the source code of your own applications.          -->

{% extends "base.html" %}

{% csrf_token %}

{% block title %} EDT {% endblock %}
{% block content %}

{% load static %}

<link rel="stylesheet" href="{% static 'base/better.css' %}?7" />
<script src="{% static 'base/d3.v4.min.js' %}"></script>
<script>
  var groupes_fi = "{% url 'api:groups:structural-tree' %}";
  var transversal_groupes_fi = "{% url 'api:groups:transversal-list' %}";

  var url_ttconstraint = "{% url 'api:ttapp:constraint-list' %}"
  var rooms_fi = "{% url 'api:rooms:all-list' %}";
  var constraints_fi = "{% url 'api:fetch:constraints-list' %}";
    
    var url_module = "{% url 'api:course:module-list' %}";
    var url_tutor = "{% url 'api:tutor-list' %}";
    var url_all_tutors = "{% url 'api:tutor_username-list' %}";
    var url_user_pref = "{% url 'api:user-actual-list' %}";
    var url_user_pref_default = "{% url 'api:user-def-list' %}";

    var url_bknews = "{% url 'api:extra:bknews-list' %}";
    var url_quote = "{% url 'api:extra:random-quote-list' %}";

  var url_cours_pp = "{% url 'api:fetch:unscheduledcourses-list' %}";

  var url_weekdays = "{% url 'api:fetch:weekdays-list' %}";
  
    var url_contact = "{% url "base:contact" department %}";
    var url_login = "{% url "people:login" %}";
    var url_edt = "{% url "base:edt" department %}";

  var url_cours_pl = "{% url 'api:fetch:scheduledcourses-list' %}";

    var url_unavailable_rooms = "{% url 'api:fetch:unavailablerooms-list' %}";

    var url_edt_changes = "{% url "base:edt_changes" department %}";
    var url_user_pref_changes = "{% url "base:user_pref_changes" department 0 0 '.' %}";
    url_user_pref_changes = url_user_pref_changes.slice(0, -5);

    var url_week_infos = "{% url 'api:extra:week-infos-list' %}";

    var url_work_copies = "{% url "TTapp:available_work_copies" department 0 0 %}" ;
    url_work_copies = url_work_copies.slice(0, -3);
    var url_check_swap = "{% url 'TTapp:check_swap' department 0 0 0 %}" ;
    url_check_swap = url_check_swap.slice(0, -5) ;
    var url_delete_work_copy = "{% url 'TTapp:delete_work_copy' department 0 0 0 %}" ;
    url_delete_work_copy = url_delete_work_copy.slice(0, -5) ;
    var url_duplicate_work_copy = "{% url 'TTapp:duplicate_work_copy' department 0 0 0 %}" ;
    url_duplicate_work_copy = url_duplicate_work_copy.slice(0, -5) ;
    var url_delete_all_unused_work_copies = "{% url 'TTapp:delete_all_unused_work_copies' department 0 0 %}" ;
    url_delete_all_unused_work_copies = url_delete_all_unused_work_copies.slice(0, -3) ;
    var url_swap = "{% url 'TTapp:swap' department 0 0 0 %}" ;
    url_swap = url_swap.slice(0, -5) ;
    var url_reassign_rooms = "{% url 'TTapp:reassign_rooms' department 0 0 0 %}" ;
    url_reassign_rooms = url_reassign_rooms.slice(0, -5) ;
    var url_fetch_extra_sched = "{% url 'api:fetch:extrasched-list' %}" ;
    {% comment %} url_fetch_extra_sched = url_fetch_extra_sched.slice(0, -3) ; {% endcomment %}
    var url_fetch_shared_rooms = "{% url 'base:fetch_shared_rooms' department 0 0 %}" ;
    url_fetch_shared_rooms = url_fetch_shared_rooms.slice(0, -3) ;
    var url_mail_auto = "{% url "base:email-proposal" department %}";
    var url_game = "{% url 'easter_egg:start_game' %}" ;
  var url_colors = "{% url 'displayweb:fetch_colors' department %}" ;
  var url_group_lunch = "{% url 'TTapp:fetch_group_lunch' department %}" ;
  var url_fetch_user_preferred_links = "{% url 'people:fetch_user_preferred_links' department %}" ;
  var url_fetch_group_preferred_links = "{% url 'base:fetch_group_preferred_links' department %}" ;
  var url_change_preferred_links = "{% url 'base:visio-pref' department %}" ;
  var url_fetch_physical_presence = "{% url 'people:fetch_physical_presence' department 0 0 %}" ;
  url_fetch_physical_presence = url_fetch_physical_presence.slice(0, -3) ;
  var url_change_physical_presence = "{% url 'people:change_physical_presence' 0 0 '.' %}" ;
  url_change_physical_presence = url_change_physical_presence.slice(0, -5) ;

    var department = "{{ dept }}" ;
    var week_year_list = {{ all_weeks| safe }};
    var week_init = +"{{ week }}";
    var year_init = +"{{ year }}";
  var department_settings = {{ department_settings | safe }} ;
  department_settings.mode['visio']=department_settings.mode['visio']=='True'?true:false;
  department_settings.time.bu = {} ;
    var days = {{ days | safe }} ;
  var csrftoken = '{{ csrf_token }}';
  if(!jQuery.fn.jquery.startsWith("1")){
      function csrfSafeMethod(method) {
          // these HTTP methods do not require CSRF protection
          return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
      }
      $.ajaxSetup({
          beforeSend: function(xhr, settings) {
              if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
              }
          }
      });
  }
</script>

{% block script_variable %}{% endblock %}

<script type='text/javascript' src="{% static 'base/helpers.js' %}"></script>
<script type='text/javascript' src="{% static 'TTapp/side_panel.js' %}"></script>
<script type='text/javascript' src="{% static 'base/days.js' %}"></script>
<script type='text/javascript' src="{% static 'base/weeks.js' %}"></script>
<script type='text/javascript' src="{% static 'base/hours.js' %}"></script>
<script type='text/javascript' src="{% static 'base/svg.js' %}"></script>
<script type='text/javascript' src="{% static 'base/variables.js' %}?9"></script>
<script type='text/javascript' src="{% static 'base/intervals.js' %}?7"></script>
<script type='text/javascript' src="{% static 'base/week_change.js' %}?7"></script>
<script type='text/javascript' src="{% static 'base/transformation.js' %}?8"></script>
<script type='text/javascript' src="{% static 'base/creation.js' %}?9"></script>
<script type='text/javascript' src="{% static 'base/action.js' %}?10"></script>
<script type='text/javascript' src="{% static 'base/update.js' %}?11"></script>

{% block script_file %}{% endblock %}

{% endblock %}