FlOpEDT/api/urls.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
# 
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.

from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.views.generic import TemplateView
from drf_yasg import openapi
# from rest_framework_swagger.renderers import SwaggerUIRenderer, OpenAPIRenderer
from drf_yasg.views import get_schema_view
from rest_framework import routers, permissions
from rest_framework.authtoken.views import obtain_auth_token

import api.base.views as views_base
import api.fetch.views as views_fetch
from api import views
from api.TTapp.urls import routerTTapp
from api.base.urls import routerBase
from api.base.rooms.urls import routerRooms
from api.base.groups.urls import routerGroups
from api.base.courses.urls import routerCourses
from api.fetch.urls import routerFetch
from api.people.urls import routerPeople
from api.preferences.urls import routerPreferences
from api.myflop.urls import routerMyFlop

#####################################
# URLS based on django applications #
#####################################

app_name = "api"

routerDisplayweb = routers.SimpleRouter()

routerDisplayweb.register(r'breakingnews', views.BreakingNewsViewSet)
routerDisplayweb.register(r'moduledisplays', views.ModuleDisplaysViewSet)
routerDisplayweb.register(r'trainingprogrammedisplays', views.TrainingProgrammeDisplaysViewSet)
routerDisplayweb.register(r'groupdisplays', views.GroupDisplaysViewSet)


######################
# User friendly URLS #
######################

routerExtra = routers.SimpleRouter()

routerExtra.register('bknews', views_fetch.BKNewsViewSet, basename="bknews")
routerExtra.register('quote/random', views.RandomQuoteViewSet, basename="random-quote")
routerExtra.register('quote', views.QuoteViewSet)
routerExtra.register('week-infos', views.WeekInfoViewSet, basename="week-infos")

################
# SWAGGER VIEW #
################
schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    url(r'^$', views_base.LoginView.as_view()),
    url(r'^logout/$', views_base.LogoutView.as_view()),
    url(r'^backoffice/$', login_required(TemplateView.as_view(template_name='logout.html'))),
    path('base/', include((routerBase.urls, 'api'), namespace='base')),
    path('user/', include(routerPeople.urls)),
    path('display/', include(routerDisplayweb.urls)),
    path('ttapp/', include((routerTTapp.urls, 'api'), namespace='ttapp')),
    path('fetch/',
         include((routerFetch.urls, 'api'), namespace='fetch')),
    path('rest-auth/', include('rest_auth.urls')),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
    url('doc/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('preferences/', include(routerPreferences.urls)),
    path('rooms/',
         include((routerRooms.urls, 'api'), namespace = 'rooms')),
    path('courses/',
         include((routerCourses.urls, 'api'), namespace = 'course')),
    path('groups/',
         include((routerGroups.urls, 'api'), namespace = 'groups')),
    path('extra/',
         include((routerExtra.urls, 'api'), namespace='extra')),
    path('myflop/',
         include((routerMyFlop.urls, 'api'), namespace='myflop')),
]

FlOpEDT/configuration/urls.py
from django.conf.urls import url
from . import views

app_name="configuration"

urlpatterns = [
    url(r'^$', views.configuration, name="configuration"),
    url(r'^upload_config/$', views.import_config_file, name="ul_config"),
    url(r'^upload_planif/$', views.import_planif_file, name="ul_planif"),
    url(r'^download_config/$', views.get_config_file, name="dl_config"),
    url(r'^download_planif/$', views.get_planif_file, name="dl_planif"),
]

FlOpEDT/flopeditor/urls.py
# -*- coding: utf-8 -*-
"""
Python versions: Python 3.6

This file is part of the FlOpEDT/FlOpScheduler project.
Copyright (c) 2017
Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public
License along with this program. If not, see
<http://www.gnu.org/licenses/>.

You can be released from the requirements of the license by purchasing
a commercial license. Buying such a license is mandatory as soon as
you develop activities involving the FlOpEDT/FlOpScheduler software
without disclosing the source code of your own applications.


This module is used to declare the urls related to flop!EDITOR, an app used
to manage a department statistics for FlOpEDT.
"""

from django.urls import path
from . import views, crud

app_name = "flopeditor"

urlpatterns = [
    # directly reachable by users
    # ---------------------------
    path('', views.home, name='flopeditor-home'),
    path('flopeditor-help/', views.flopeditor_help, name='flopeditor-help'),
    path('<slug:department_abbrev>/', views.department_default,
         name='flopeditor-department-default'),
    path('<slug:department_abbrev>/salles', views.department_rooms,
         name='flopeditor-department-rooms'),
    path('<slug:department_abbrev>/intervenants', views.department_tutors,
         name='flopeditor-department-tutors'),
    path('<slug:department_abbrev>/categories-de-salles', views.department_room_types,
         name='flopeditor-department-room-types'),
    path('<slug:department_abbrev>/groupes-structuraux', views.department_student_structural_groups,
         name='flopeditor-department-student-structural-groups'),
    path('<slug:department_abbrev>/groupes-transversaux', views.department_student_transversal_groups,
         name='flopeditor-department-student-transversal-groups'),
    path('<slug:department_abbrev>/natures', views.department_student_group_types,
         name='flopeditor-department-student-group-types'),
    path('<slug:department_abbrev>/promos', views.department_training_programmes,
         name='flopeditor-department-training-programmes'),
    path('<slug:department_abbrev>/modules', views.department_modules,
         name='flopeditor-department-modules'),
    path('<slug:department_abbrev>/types-de-cours', views.department_course_types,
         name='flopeditor-department-course-types'),
    path('<slug:department_abbrev>/semestres', views.department_periods,
         name='flopeditor-department-periods'),

    path('<slug:department_abbrev>/parameters', views.department_parameters,
         name='flopeditor-department-parameters'),
    path('<slug:department_abbrev>/parameters/edit', views.department_parameters_edit,
         name='flopeditor-department-parameters-edit'),



    # exchanges with the db via django
    # --------------------------------
    path('ajax/create-department', views.ajax_create_department,
         name="flopeditor-ajax-create-department"),
    path('ajax/update-department', views.ajax_update_department,
         name="flopeditor-ajax-update-department"),
    path('ajax/parameters-edit/<slug:department_abbrev>', views.ajax_edit_parameters,
         name='flopeditor-ajax-edit-department-parameters'),
    path('ajax/update-profil', views.ajax_update_profil,
         name='flopeditor-ajax-update-profil'),

    # exchanges with the CRUD
    # --------------------------------
    path('<slug:department_abbrev>/crud/rooms', crud.crud_rooms,
         name='flopeditor-crud-rooms'),
    path('<slug:department_abbrev>/crud/tutors', crud.crud_tutors,
         name='flopeditor-crud-tutors'),
    path('<slug:department_abbrev>/crud/room_types', crud.crud_room_types,
         name='flopeditor-crud-room-types'),
    path('<slug:department_abbrev>/crud/group_type', crud.crud_student_group_type,
         name='flopeditor-crud-student-group-type'),
    path('<slug:department_abbrev>/crud/student_structural_group', crud.crud_student_structural_group,
         name='flopeditor-crud-student-structural-group'),
    path('<slug:department_abbrev>/crud/student_transversal_group', crud.crud_student_transversal_group,
         name='flopeditor-crud-student-transversal-group'),
    path('<slug:department_abbrev>/crud/modules', crud.crud_module,
         name='flopeditor-crud-modules'),
    path('<slug:department_abbrev>/crud/training_programmes', crud.crud_training_programmes,
         name='flopeditor-crud-training-programmes'),
    path('<slug:department_abbrev>/crud/courses', crud.crud_course,
         name='flopeditor-crud-courses'),
    path('<slug:department_abbrev>/crud/periods', crud.crud_periods,
         name='flopeditor-crud-periods'),

]

FlOpEDT/configuration/models.py
from django.db import models

# Create your models here.

FlOpEDT/configuration/forms.py
from django import forms
from django.core.files.storage import FileSystemStorage
from django.core.validators import RegexValidator
from base.models import Department

DAYS = [('m', 'Monday'), ('tu', 'Tuesday'), ('w', 'Wenesday'), ('th', 'Thursday'), ('f', 'Friday')]

validator_time = RegexValidator(r"^\d{2}:\d{2}$", "Must be as 00:00")


class ImportFile(forms.Form):
    file = forms.FileField()


class ImportPlanif(forms.Form):
    fichier = forms.FileField()


class ImportConfig(forms.Form):
    # nom = forms.SlugField()
    # abbrev = forms.CharField(max_length=7)
    # day_start_time = forms.CharField(max_length=5, min_length=5, validators=[validator_time])
    # day_end_time = forms.CharField(max_length=5, min_length=5, validators=[validator_time])
    # lunch_start_time = forms.CharField(max_length=5, min_length=5, validators=[validator_time])
    # lunch_end_time = forms.CharField(max_length=5, min_length=5, validators=[validator_time])
    # days = forms.MultipleChoiceField(
    #     required=True,
    #     widget=forms.CheckboxSelectMultiple,
    #     choices=DAYS,
    # )
    fichier = forms.FileField()

FlOpEDT/configuration/templates/configuration/configuration.html
{% extends "base.html" %}

{% block title %} EDT {% endblock %}
{% block content %}
    {% load static %}
    {% load i18n %}
    <link rel="stylesheet" href="{% static 'configuration/style.css' %}"/>
    <script>
        let departements = {{ departements|safe }};
        let periods = {{ periods|safe }};
        let current_year = {{ current_year }};
        let next_year = {{current_year|add:"1"}};
    </script>
    <script type="text/javascript" src="{% static 'configuration/configuration_vars.js' %}"></script>
    <h1>{% trans "Step 1 - Database configuration (teachers, groups, rooms, course types, etc.)" %}</h1>
    <h2>{% trans "Option A: Using a spreadsheet file" %}</h2>
    <div class="step">
        <h3>{% trans "Configuration file canvas" %}</h3>
        <p>{% trans "Download and then complete the file below." %}</p>
            {% trans "Click to download the configuration file" %}
            <a href="{% url "configuration:dl_config" %}"><button id="btn_config_1">{% trans "Download"%}</button></a>
    </div>

    <div class="step">
        <h3>{% trans "Configuration file completed" %}</h3>
        <p>{% trans "Upload the completed configuration file." %}<br>
        {% trans "Only xlsx format is accepted."%}</p>
        <form action="{% url "configuration:ul_config" %}" method="post" enctype="multipart/form-data" id="config">
                {% csrf_token %}
            <fieldset>
                <label>{% trans "Department" %}</label><br>
                <input type="radio" name="radio_creations" value="1" required><span>{% trans "Create" %}</span>
                <input type="radio" name="radio_creations" value="2" required><span>{% trans "Edit" %}</span><br>
                <div id="depart_choice"></div>
                {{ form_config }}
                <input type="submit" value={% trans "Import" %}>
            </fieldset>
        </form>

        <div id="error_config">
          <h4>{% trans "Verdict :"%}</h4>
          <p></p>
        </div>
    </div>
    <h2>{% trans "Option B: With Flopeditor" %}</h2>
    <div class="step">
      <p><a href="{% url 'flopeditor:flopeditor-home' %}">{% trans "Click here" %}</a> {% trans " to go to Flopeditor."%} <br>
      {% trans "If you need help, you can consult the Flopeditor documentation on " %} <a href="{% url 'flopeditor:flopeditor-help' %}">{% trans "this page." %}</a>.</p>
    </div>

    <h1>{% trans "Step 2 - Plan the lessons (which lesson in which week, which teacher gives which lesson)" %}</h1>
    <div class="step">
    <h3>{% trans "Template for the planning file from the configuration file" %}</h3>
        <p>{% trans "Download and then complete the file below." %}</p>
        {% trans "Click to download the planning file outline" %}
        <form action="{% url "configuration:dl_planif" %}">
        <select name="departement"  id="dropdown_dpt_1">
            {% for depart in departements %}
                <option value={{ depart.abbrev }} >{{ depart.name }}</option>
            {% endfor %}
        </select>
        <input id="btn_dl_planif" type="submit" value={% trans "Download" %}>
        </form>
    </div>

    <div class="step">
<!--        <form action="/configuration/import_planif_file/" method="post" enctype="multipart/form-data" id="config_2">-->
        <fieldset>
            <legend> <h3>{% trans "Completed planning file" %}</h3> </legend>
            <p>{% trans "Upload the completed planning file." %} ({% trans "Only xlsx format is accepted." %})</p>
            <form action="{% url "configuration:ul_planif" %}"
                  method="post"
                  enctype="multipart/form-data"
                  id="planif">
                {% csrf_token %}
                <select name="departement" id="dropdown_dpt_2">
                    {% for depart in departements %}
                        <option value={{ depart.abbrev }} >{{ depart.name }}</option>
                    {% endfor %}
                </select>
                </br></br>
                {{ form_planif }}
                </br></br>
                <div id="choose_weeks">
                    <input type="checkbox" id="choose_weeks" name="choose_weeks"/>
                    <label for="choose_weeks">
                        {% trans "From week" %}
                        <input type="number" name="week_nb" style="width: 40px" min="1" max="53" id="1">
                        {% trans "year" %}
                        <input type="number" name="year" style="width: 60px" value="{{current_year}}" min="{{current_year}}" max="{{current_year|add:"1"}}" id="3">
                        </br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        {% trans "until week" %}
                        <input type="number" name="week_nb_end" style="width: 40px" min="1" max="53" id="5">
                        {% trans "year" %}
                    </label>
                    <input type="number" name="year_end" style="width: 60px" value="{{current_year|add:"1"}}" min="{{current_year}}" max="{{current_year|add:"1"}}" id="7">
                </div>
                </br>
                <div id="choose_periods">
                <input type="checkbox" id="choose_periods" name="choose_periods"/>
                    <label for="choose_periods">{% trans "Only for periods " %}
                        <select multiple name="periods" id="dropdown_periods"> </select>
                    </label>
                </div>
                </br></br>
                <input type="checkbox" id="stabilize" name="stabilize"/>
                <label for="stabilize">{% trans "Stabilization ?" %}</label>
                </br></br>
                <input type="submit"
                       id="submitImport"
                       onclick="return confirm(
                           confirm_text.intro + '\n\n' +
                           translated_department + confirm_text.department + '\n' +
                           translated_periods + confirm_text.periods + '\n' +
                           translated_weeks + confirm_text.weeks)"
                       value={% trans "Import" %}>
            </form>
        </fieldset>
        <div id="error_planif">
          <h4>{% trans "Verdict :" %}</h4>
          <p></p>
        </div>
    </div>

<script type="text/javascript" src="{% static 'configuration/configuration.js' %}"></script>
{% endblock %}