FlOpEDT/api/base/rooms/urls.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
#
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.
from rest_framework import routers

from api.base.rooms import views

routerRooms = routers.SimpleRouter()

routerRooms.register(r'types', views.RoomTypesViewSet)
routerRooms.register(r'names', views.RoomNameViewSet)
routerRooms.register(r'room', views.RoomViewSet)
routerRooms.register(r'all', views.RoomAllViewSet, basename='all')
routerRooms.register(r'sorts', views.RoomSortsViewSet)

FlOpEDT/api/base/urls.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
#
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.
from rest_framework import routers

from api.base import views

routerBase = routers.SimpleRouter()

# routerBase.register(r'studentspreferences', views.StudentPreferencesViewSet, basename="students")
# routerBase.register(r'groupspreferences', views.GroupPreferencesViewSet)

# routerBase.register(r'departments', views.DepartmentViewSet)
routerBase.register(r'trainingprogram/name', views.TrainingProgrammeNameViewSet, basename='trainingprogramme-name')
# routerBase.register(r'trainingprogram', views.TrainingProgrammeViewSet)
# routerBase.register(r'holidays', views.HolidaysViewSet)
# routerBase.register(r'traininghalfdays', views.TrainingHalfDaysViewSet)
# routerBase.register(r'periods', views.PeriodsViewSet)
# routerBase.register(r'timesettings', views.TimeGeneralSettingsViewSet)
# routerBase.register(r'edtversions', views.EdtVersionsViewSet)
# routerBase.register(r'coursemodifications', views.CourseModificationsViewSet)
# routerBase.register(r'tutorcosts', views.TutorCostsViewSet)
# routerBase.register(r'groupcosts', views.GroupCostsViewSet)
# routerBase.register(r'CourseStartTimeFilter', views.GroupFreeHalfDaysViewSet)
# routerBase.register(r'dependencies', views.DependenciesViewSet)
# routerBase.register(r'coursesstarttimeconstraints', views.CourseStartTimeConstraintsViewSet)
# routerBase.register(r'regens', views.RegensViewSet)
# routerBase.register(r'login', views.LoginView, basename="login")
# routerBase.register(r'logout', views.LogoutView, basename="logout")

FlOpEDT/api/urls.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
# 
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.

from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.views.generic import TemplateView
from drf_yasg import openapi
# from rest_framework_swagger.renderers import SwaggerUIRenderer, OpenAPIRenderer
from drf_yasg.views import get_schema_view
from rest_framework import routers, permissions
from rest_framework.authtoken.views import obtain_auth_token

import api.base.views as views_base
import api.fetch.views as views_fetch
from api import views
from api.TTapp.urls import routerTTapp
from api.base.urls import routerBase
from api.base.rooms.urls import routerRooms
from api.base.groups.urls import routerGroups
from api.base.courses.urls import routerCourses
from api.fetch.urls import routerFetch
from api.people.urls import routerPeople
from api.preferences.urls import routerPreferences
from api.myflop.urls import routerMyFlop

#####################################
# URLS based on django applications #
#####################################

app_name = "api"

routerDisplayweb = routers.SimpleRouter()

routerDisplayweb.register(r'breakingnews', views.BreakingNewsViewSet)
routerDisplayweb.register(r'moduledisplays', views.ModuleDisplaysViewSet)
routerDisplayweb.register(r'trainingprogrammedisplays', views.TrainingProgrammeDisplaysViewSet)
routerDisplayweb.register(r'groupdisplays', views.GroupDisplaysViewSet)


######################
# User friendly URLS #
######################

routerExtra = routers.SimpleRouter()

routerExtra.register('bknews', views_fetch.BKNewsViewSet, basename="bknews")
routerExtra.register('quote/random', views.RandomQuoteViewSet, basename="random-quote")
routerExtra.register('quote', views.QuoteViewSet)
routerExtra.register('week-infos', views.WeekInfoViewSet, basename="week-infos")

################
# SWAGGER VIEW #
################
schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    url(r'^$', views_base.LoginView.as_view()),
    url(r'^logout/$', views_base.LogoutView.as_view()),
    url(r'^backoffice/$', login_required(TemplateView.as_view(template_name='logout.html'))),
    path('base/', include((routerBase.urls, 'api'), namespace='base')),
    path('user/', include(routerPeople.urls)),
    path('display/', include(routerDisplayweb.urls)),
    path('ttapp/', include((routerTTapp.urls, 'api'), namespace='ttapp')),
    path('fetch/',
         include((routerFetch.urls, 'api'), namespace='fetch')),
    path('rest-auth/', include('rest_auth.urls')),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
    url('doc/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('preferences/', include(routerPreferences.urls)),
    path('rooms/',
         include((routerRooms.urls, 'api'), namespace = 'rooms')),
    path('courses/',
         include((routerCourses.urls, 'api'), namespace = 'course')),
    path('groups/',
         include((routerGroups.urls, 'api'), namespace = 'groups')),
    path('extra/',
         include((routerExtra.urls, 'api'), namespace='extra')),
    path('myflop/',
         include((routerMyFlop.urls, 'api'), namespace='myflop')),
]

FlOpEDT/base/urls.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
# 
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.

from django.conf.urls import url, include
from django.urls import path, re_path
from . import views
from . import statistics
from django.views.generic import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

app_name="base"

urlpatterns = [
    # favicon
    # ----------------------------
    url(views.fav_regexp,
        views.favicon,
        name="favicon"),

    # directly reachable by users
    # ----------------------------
    re_path(r'room-preference/(?P<tutor>\w{2,8})?', views.room_preference, name='room-pref'),
    re_path(r'visio-preference/(?P<tutor>\w{1,8})?(/?P<id>\d{1,8})?',
            views.visio_preference,
            name='visio-pref'),

    url(r'^preferences$', views.preferences, name="preferences"),
    url(r'^semaine-type$', views.stype, name="stype"),
    url(r'^aide$', views.aide, name="aide"),
    url(r'^decale$', views.decale, name="decale"),    
    url(r'^contact/(?P<tutor>\w{2,8})?$', views.contact, name="contact"),
    url(r'^module_description(/(?P<module>\w{1,8}))?$', views.module_description, name="module_description"),
    url(r'^((?P<year>\d{4}))?(/(?P<week>\d{1,2}))?$', views.edt, name="edt"),
    url(r'^tv(/(?P<year>\d+))?(/(?P<week>\d+))?$', views.edt_light, name="edt_light"),
    url(r'^modules$', views.all_modules_with_desc, name="modules"),
    #Send Email to teacher when student want modify schedule
    url(r'^email-modif$', views.send_email_proposal, name='email-proposal'),

    # exchanges with the db via django
    # ---------------------------------

    # from db to screen
    path('fetch_user_default_week/<str:username>', views.fetch_user_default_week, name="fetch_user_dweek"),
    path('fetch_course_default_week/<str:train_prog>/<str:course_type>', views.fetch_course_default_week, name="fetch_course_dweek"),
    path('fetch_room_default_week/<str:room>', views.fetch_room_default_week, name="fetch_room_dweek"),
    url(r'^fetch_decale$', views.fetch_decale, name="fetch_decale"),
    url(r'^fetch_bknews/(?P<year>\d+)/(?P<week>\d+)$', views.fetch_bknews, name="fetch_bknews"),
    url(r'^fetch_groups$', views.fetch_groups, name="fetch_groups"),    
    url(r'^fetch_rooms$', views.fetch_rooms, name="fetch_rooms"),    
    url(r'^fetch_flat_rooms$', views.fetch_flat_rooms, name="fetch_flat_rooms"),    
    url(r'^fetch_constraints$', views.fetch_constraints, name="fetch_constraints"),
    path('fetch_course_types', views.fetch_course_types, name="fetch_course_types"),
    path('fetch_training_programmes', views.fetch_training_programmes, name="fetch_training_programmes"),
    url(r'^fetch_unavailable_rooms/(?P<year>\d+)/(?P<week>\d+)$', views.fetch_unavailable_rooms, name="fetch_unavailable_rooms"),
    url(r'^fetch_all_tutors/$', views.fetch_all_tutors, name="fetch_all_tutors"),
    url(r'^fetch_all_versions/$', views.fetch_all_versions, name="fetch_all_versions"),
    path('fetch_departments', views.fetch_departments, name="fetch_departments"),
    path('fetch_tutor_courses/<int:year>/<int:week>/<str:tutor>', views.fetch_tutor_courses, name="fetch_tutor_courses"),
    path('fetch_extra_sched/<int:year>/<int:week>', views.fetch_extra_sched, name="fetch_extra_sched"),
    path('fetch_shared_rooms/<int:year>/<int:week>', views.fetch_shared_rooms, name="fetch_shared_rooms"),
    path('fetch_perfect_day/<str:username>', views.fetch_perfect_day, name="fetch_perfect_day"),
    path('fetch_user_notifications_pref/<str:username>', views.fetch_user_notifications_pref, name="fetch_user_notifications_pref"),
    url(r'^fetch_module/(?P<year>\d+)/(?P<week>\d+)$', views.fetch_module, name="fetch_module"),
    url(r'^fetch_tutors/(?P<year>\d+)/(?P<week>\d+)$', views.fetch_tutor, name="fetch_tutor"),
    url(r'^fetch_all_modules_with_desc$', views.fetch_all_modules_with_desc, name="fetch_all_modules_with_desc"),
    url(r'^fetch_all_dispos$', views.fetch_all_dispos, name="fetch_all_dispos"),
    path('fetch_group_preferred_links',
         views.fetch_group_preferred_links,
         name='fetch_group_preferred_links'),

    # statistics
    # ---------------------------------
    path('statistics/', include([
        path('', statistics.index, name="statistics"),
        path('rooms/', statistics.fetch_room_activity, name="room_activity"),
        path('tutors/', statistics.fetch_tutor_hours, name="tutor_hours"),
        path('groups/', statistics.fetch_group_hours, name="group_hours"),
    ])),

    # from screen to db
    path('change_edt', views.edt_changes, name="edt_changes"),
    path('change_user_pref/<int:year>/<int:week>/<str:username>',
         views.user_preferences_changes,
         name="user_pref_changes"),
    path('change_course_pref/<int:year>/<int:week>/<str:train_prog>/<str:course_type>', views.course_preferences_changes, name="course_pref_changes"),
    path('change_room_pref/<int:year>/<int:week>/<str:room>',
         views.room_preferences_changes,
         name="room_pref_changes"),
    path('change_decale', views.decale_changes, name="decale_changes"),
    path('change_perfect_day/<str:username>',
         views.user_perfect_day_changes,
         name="user_perfect_day_changes"),
    path('change_user_notifications_pref/<str:username>',
         views.user_notifications_pref_changes,
         name="user_notifications_pref_changes"),
    path(r'change_room_pref_per_tutor/<str:tutor>',
         views.room_preferences_changes_per_tutor,
         name='room_pref_changes_per_tutor'),

    # predefined
    # ------------
]

# https://pypi.python.org/pypi/django-live-log
# https://github.com/abdullatheef/django_live_log

FlOpEDT/ics/urls.py
from django.urls import path
from ics.feeds import TutorEventFeed, RoomEventFeed, StructuralGroupEventFeed, TransversalGroupEventFeed, RegenFeed

from ics import views

app_name = 'ics'

urlpatterns = [
    path(r'', views.index, name="index"),
    path(r'tutor/<int:tutor_id>.ics', TutorEventFeed(), name="tutor"),
    path(r'room/<int:room_id>.ics', RoomEventFeed(), name="room"),
    path(r'structural_group/<int:group_id>.ics', StructuralGroupEventFeed(), name="structural_group"),
    path(r'transversal_group/<int:group_id>.ics', TransversalGroupEventFeed(), name="transversal_group"),
    path(r'regen/<int:dep_id>.ics', RegenFeed(), name="regen"),
]

FlOpEDT/solve_board/urls.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
# 
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.

from django.conf.urls import url, include

from solve_board import views

app_name="solve_board"

urlpatterns = [
    url(r'^fetch_context/(?P<train_prog>[a-zA-Z]\w{1,4})/(?P<year>\d{4})/(?P<week>\d{1,2})/$', views.fetch_context, name="fetch_context"),
    url(r'^main/$', views.main_board, name="main_board"),
    url(r'^analyse/(?P<train_prog>[a-zA-Z]\w{1,4})/(?P<year>\d{4})/(?P<week>\d{1,2})/(?P<type>[a-zA-Z]\w{1,30})$', views.launch_pre_analyse, name="pre_analyse")
#    url(r'^run/(?P<timestamp>[0-9-]+)?$', views.run, name="run"),
]

FlOpEDT/templates/base.html
<!-- This file is part of the FlOpEDT/FlOpScheduler project.               -->
<!-- Copyright (c) 2017                                                    -->
<!-- Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.           -->
<!--                                                                       -->
<!-- This program is free software: you can redistribute it and/or modify  -->
<!-- it under the terms of the GNU Affero General Public License as        -->
<!-- published by the Free Software Foundation, either version 3 of the    -->
<!-- License, or (at your option) any later version.                       -->
<!--                                                                       -->
<!-- This program is distributed in the hope that it will be useful, but   -->
<!-- WITHOUT ANY WARRANTY; without even the implied warranty of            -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU      -->
<!-- Affero General Public License for more details.                       -->
<!--                                                                       -->
<!-- You should have received a copy of the GNU Affero General Public      -->
<!-- License along with this program. If not, see                          -->
<!-- <http://www.gnu.org/licenses/>.                                       -->
<!--                                                                       -->
<!-- You can be released from the requirements of the license by purchasing-->
<!-- a commercial license. Buying such a license is mandatory as soon as   -->
<!-- you develop activities involving the FlOpEDT/FlOpScheduler software   -->
<!-- without disclosing the source code of your own applications.          -->

{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
<head>
<style>
</style>
<link rel="stylesheet" href="{% static 'base/header.css' %}?2" />
<link rel="stylesheet" href="{% static 'TTapp/styles.css' %}" />
<link rel="apple-touch-icon" sizes="180x180" href=" /static/base/img/favicons/apple-touch-icon.png?v=5AeyQYqgW7">
<link rel="icon" type="image/png" sizes="32x32" href=" /static/base/img/favicons/favicon-32x32.png?v=5AeyQYqgW7">
<link rel="icon" type="image/png" sizes="16x16" href=" /static/base/img/favicons/favicon-16x16.png?v=5AeyQYqgW7">
<link rel="manifest" href=" /static/base/img/favicons/site.webmanifest?v=5AeyQYqgW7">
<link rel="mask-icon" href=" /static/base/img/favicons/safari-pinned-tab.svg?v=5AeyQYqgW7" color="#858585">
<link rel="shortcut icon" href=" /static/base/img/favicons/favicon.ico?v=5AeyQYqgW7">
<meta charset="UTF-8">
<meta name="msapplication-TileColor" content="#048c04">
<meta name="theme-color" content="#000000">

<script src="{% url 'javascript-catalog' %}"></script>
{% block jquery %}
<script src="{% static 'base/jquery.min.js' %}"></script>
{% endblock %}
<script src="{% static 'base/d3.v4.min.js' %}"></script>
<script src="{% static 'base/loader.js' %}"></script>
<script>var url_logo = "{% static 'base/logo-clock.svg' %}";</script>
<!-- script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script -->
<title>{% block title %}{% trans "Schedule_title" %}{% endblock %}</title>
</head>
<body>
  {% block loader %}
  <div id="loader" class="loader" style="visibility:hidden;"></div>
  {% endblock %}
  <!--<header>Emplois du temps</header>-->
  {% block full_nav %}
  <nav id="menu-edt">
    <a class="hide_this_link" id="live-logo"  style="padding: 0px 0px 0px 0px; float: left" >
    </a>
    <div id="full_logo">
      <a style="text-decoration: none; font-family: inherit; color: inherit" href="{% url 'index' %}">
          <span id="acro_logo">{% trans "<span id=flopGreen >flop</span>!<span id=EDTRed >Scheduler</span>" %}</span>
      </a>
      {% autoescape off %}
      <span id="head_logo"></span>
      {% endautoescape %}
      <a id="agpl" target="_blank" href="https://framagit.org/flopedt/flopedt">
	      <img src="{% static 'base/agplv3-88x31.png'%}" height="31" width="88" alt="AGPL v.3"/>
      </a>
    </div>

    {% block nav %}
    <ul>
      {% if request.department %}
      {% if request.is_department_admin %}
      <li><a href="#" onclick="openNav()">☰</a></li>
      {% endif %}
      <li><a href="{% url "base:edt" department %}">{% trans 'Schedule_banner' %}</a></li>
      {% if request.has_department_perm %}
      <li><a href="{% url "base:decale" department %}">{% trans 'Move/Cancel' %}</a></li>
      {% endif %}
      <li><a href="{% url "base:preferences" department %}">{% trans 'Preferences' %}</a></li>
      <li><a href="{% url "ics:index" department %}">{% trans 'iCal' %}</a></li>
      <li><a href="{% url "base:aide" department %}">{% trans 'Help' %}</a></li>
      <li><a href="{% url "base:contact" department %}">{% trans 'Messages' %}</a></li>
      <li><a href="{% url "base:modules" department %}">{% trans 'Modules' %}</a></li>
      {% if request.is_department_admin %}
          <li><a href="{% url "solve_board:main_board" department %}">{% trans 'Generate' %}</a></li>
          <li><a href="{% url "flopeditor:flopeditor-department-default" department %}">{% trans 'flop!EDITOR' %}</a></li>
          <li><a href="{% url "base:statistics" department %}">{% trans 'Statistics' %}</a></li>
          <li><a href="{% url "configuration:configuration" %}">{% trans 'Import'%}</a></li>
          <li><a href="{% url "admin:index" %}">{% trans 'Admin'%}</a></li>
      {% endif %}
      {% endif %}
      <li style="float:right">
	{% if user.is_authenticated %}
	{% if request.department %}
	<a href="{% url "people:logout" %}?next={% url "base:edt" department %}">{% trans 'Sign out' %}</a>
	{% elif not 'accounts' in request.path %}
	<a href="{% url "people:logout" %}?next={{request.path}}">{% trans 'Sign out' %}</a>
	{% else %}
	<a href="{% url "people:logout" %}">{% trans "Sign out" %}</a>
	{% endif %}
	{% else %}
	<a href="{% url "people:login" %}?next={{request.path}}" id='sign_in'>{% trans 'Sign in' %}</a>
	{% endif %}
      </li>
      <li style="float:right">{% if user.is_authenticated %}
	<a href="{% url "people:change_redirect" %}">{% trans 'Signed in as ' %} {{ user.username }}</a> {% endif %}
      </li>
    </ul>
    {% endblock %}
  </nav>
  {% endblock %}
  <section id="content">
    {% block content %}{% endblock %}
    <div id="side_panel" class="sidebar">
      <a href="javascript:void(0)" class="btn_panel" onclick="closeNav()">×</a>
      {% block side_panel %} {% endblock %}
    </div>
  </section>

  {% block logo %}
  <script src="{% static 'base/logo.js' %}"></script>
  {% endblock %}
  <script>

  </script>
  {% block javascript %}
  {% endblock %}
</body>
</html>