FlOpEDT/api/base/urls.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
#
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.
from rest_framework import routers

from api.base import views

routerBase = routers.SimpleRouter()

# routerBase.register(r'studentspreferences', views.StudentPreferencesViewSet, basename="students")
# routerBase.register(r'groupspreferences', views.GroupPreferencesViewSet)

# routerBase.register(r'departments', views.DepartmentViewSet)
routerBase.register(r'trainingprogram/name', views.TrainingProgrammeNameViewSet, basename='trainingprogramme-name')
# routerBase.register(r'trainingprogram', views.TrainingProgrammeViewSet)
# routerBase.register(r'holidays', views.HolidaysViewSet)
# routerBase.register(r'traininghalfdays', views.TrainingHalfDaysViewSet)
# routerBase.register(r'periods', views.PeriodsViewSet)
# routerBase.register(r'timesettings', views.TimeGeneralSettingsViewSet)
# routerBase.register(r'edtversions', views.EdtVersionsViewSet)
# routerBase.register(r'coursemodifications', views.CourseModificationsViewSet)
# routerBase.register(r'tutorcosts', views.TutorCostsViewSet)
# routerBase.register(r'groupcosts', views.GroupCostsViewSet)
# routerBase.register(r'CourseStartTimeFilter', views.GroupFreeHalfDaysViewSet)
# routerBase.register(r'dependencies', views.DependenciesViewSet)
# routerBase.register(r'coursesstarttimeconstraints', views.CourseStartTimeConstraintsViewSet)
# routerBase.register(r'regens', views.RegensViewSet)
# routerBase.register(r'login', views.LoginView, basename="login")
# routerBase.register(r'logout', views.LogoutView, basename="logout")

FlOpEDT/api/urls.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
# 
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.

from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.views.generic import TemplateView
from drf_yasg import openapi
# from rest_framework_swagger.renderers import SwaggerUIRenderer, OpenAPIRenderer
from drf_yasg.views import get_schema_view
from rest_framework import routers, permissions
from rest_framework.authtoken.views import obtain_auth_token

import api.base.views as views_base
import api.fetch.views as views_fetch
from api import views
from api.TTapp.urls import routerTTapp
from api.base.urls import routerBase
from api.base.rooms.urls import routerRooms
from api.base.groups.urls import routerGroups
from api.base.courses.urls import routerCourses
from api.fetch.urls import routerFetch
from api.people.urls import routerPeople
from api.preferences.urls import routerPreferences
from api.myflop.urls import routerMyFlop

#####################################
# URLS based on django applications #
#####################################

app_name = "api"

routerDisplayweb = routers.SimpleRouter()

routerDisplayweb.register(r'breakingnews', views.BreakingNewsViewSet)
routerDisplayweb.register(r'moduledisplays', views.ModuleDisplaysViewSet)
routerDisplayweb.register(r'trainingprogrammedisplays', views.TrainingProgrammeDisplaysViewSet)
routerDisplayweb.register(r'groupdisplays', views.GroupDisplaysViewSet)


######################
# User friendly URLS #
######################

routerExtra = routers.SimpleRouter()

routerExtra.register('bknews', views_fetch.BKNewsViewSet, basename="bknews")
routerExtra.register('quote/random', views.RandomQuoteViewSet, basename="random-quote")
routerExtra.register('quote', views.QuoteViewSet)
routerExtra.register('week-infos', views.WeekInfoViewSet, basename="week-infos")

################
# SWAGGER VIEW #
################
schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    url(r'^$', views_base.LoginView.as_view()),
    url(r'^logout/$', views_base.LogoutView.as_view()),
    url(r'^backoffice/$', login_required(TemplateView.as_view(template_name='logout.html'))),
    path('base/', include((routerBase.urls, 'api'), namespace='base')),
    path('user/', include(routerPeople.urls)),
    path('display/', include(routerDisplayweb.urls)),
    path('ttapp/', include((routerTTapp.urls, 'api'), namespace='ttapp')),
    path('fetch/',
         include((routerFetch.urls, 'api'), namespace='fetch')),
    path('rest-auth/', include('rest_auth.urls')),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
    url('doc/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('preferences/', include(routerPreferences.urls)),
    path('rooms/',
         include((routerRooms.urls, 'api'), namespace = 'rooms')),
    path('courses/',
         include((routerCourses.urls, 'api'), namespace = 'course')),
    path('groups/',
         include((routerGroups.urls, 'api'), namespace = 'groups')),
    path('extra/',
         include((routerExtra.urls, 'api'), namespace='extra')),
    path('myflop/',
         include((routerMyFlop.urls, 'api'), namespace='myflop')),
]

FlOpEDT/base/urls.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
# 
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.

from django.conf.urls import url, include
from django.urls import path, re_path
from . import views
from . import statistics
from django.views.generic import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

app_name="base"

urlpatterns = [
    # favicon
    # ----------------------------
    url(views.fav_regexp,
        views.favicon,
        name="favicon"),

    # directly reachable by users
    # ----------------------------
    re_path(r'room-preference/(?P<tutor>\w{2,8})?', views.room_preference, name='room-pref'),
    re_path(r'visio-preference/(?P<tutor>\w{1,8})?(/?P<id>\d{1,8})?',
            views.visio_preference,
            name='visio-pref'),

    url(r'^preferences$', views.preferences, name="preferences"),
    url(r'^semaine-type$', views.stype, name="stype"),
    url(r'^aide$', views.aide, name="aide"),
    url(r'^decale$', views.decale, name="decale"),    
    url(r'^contact/(?P<tutor>\w{2,8})?$', views.contact, name="contact"),
    url(r'^module_description(/(?P<module>\w{1,8}))?$', views.module_description, name="module_description"),
    url(r'^((?P<year>\d{4}))?(/(?P<week>\d{1,2}))?$', views.edt, name="edt"),
    url(r'^tv(/(?P<year>\d+))?(/(?P<week>\d+))?$', views.edt_light, name="edt_light"),
    url(r'^modules$', views.all_modules_with_desc, name="modules"),
    #Send Email to teacher when student want modify schedule
    url(r'^email-modif$', views.send_email_proposal, name='email-proposal'),

    # exchanges with the db via django
    # ---------------------------------

    # from db to screen
    path('fetch_user_default_week/<str:username>', views.fetch_user_default_week, name="fetch_user_dweek"),
    path('fetch_course_default_week/<str:train_prog>/<str:course_type>', views.fetch_course_default_week, name="fetch_course_dweek"),
    path('fetch_room_default_week/<str:room>', views.fetch_room_default_week, name="fetch_room_dweek"),
    url(r'^fetch_decale$', views.fetch_decale, name="fetch_decale"),
    url(r'^fetch_bknews/(?P<year>\d+)/(?P<week>\d+)$', views.fetch_bknews, name="fetch_bknews"),
    url(r'^fetch_groups$', views.fetch_groups, name="fetch_groups"),    
    url(r'^fetch_rooms$', views.fetch_rooms, name="fetch_rooms"),    
    url(r'^fetch_flat_rooms$', views.fetch_flat_rooms, name="fetch_flat_rooms"),    
    url(r'^fetch_constraints$', views.fetch_constraints, name="fetch_constraints"),
    path('fetch_course_types', views.fetch_course_types, name="fetch_course_types"),
    path('fetch_training_programmes', views.fetch_training_programmes, name="fetch_training_programmes"),
    url(r'^fetch_unavailable_rooms/(?P<year>\d+)/(?P<week>\d+)$', views.fetch_unavailable_rooms, name="fetch_unavailable_rooms"),
    url(r'^fetch_all_tutors/$', views.fetch_all_tutors, name="fetch_all_tutors"),
    url(r'^fetch_all_versions/$', views.fetch_all_versions, name="fetch_all_versions"),
    path('fetch_departments', views.fetch_departments, name="fetch_departments"),
    path('fetch_tutor_courses/<int:year>/<int:week>/<str:tutor>', views.fetch_tutor_courses, name="fetch_tutor_courses"),
    path('fetch_extra_sched/<int:year>/<int:week>', views.fetch_extra_sched, name="fetch_extra_sched"),
    path('fetch_shared_rooms/<int:year>/<int:week>', views.fetch_shared_rooms, name="fetch_shared_rooms"),
    path('fetch_perfect_day/<str:username>', views.fetch_perfect_day, name="fetch_perfect_day"),
    path('fetch_user_notifications_pref/<str:username>', views.fetch_user_notifications_pref, name="fetch_user_notifications_pref"),
    url(r'^fetch_module/(?P<year>\d+)/(?P<week>\d+)$', views.fetch_module, name="fetch_module"),
    url(r'^fetch_tutors/(?P<year>\d+)/(?P<week>\d+)$', views.fetch_tutor, name="fetch_tutor"),
    url(r'^fetch_all_modules_with_desc$', views.fetch_all_modules_with_desc, name="fetch_all_modules_with_desc"),
    url(r'^fetch_all_dispos$', views.fetch_all_dispos, name="fetch_all_dispos"),
    path('fetch_group_preferred_links',
         views.fetch_group_preferred_links,
         name='fetch_group_preferred_links'),

    # statistics
    # ---------------------------------
    path('statistics/', include([
        path('', statistics.index, name="statistics"),
        path('rooms/', statistics.fetch_room_activity, name="room_activity"),
        path('tutors/', statistics.fetch_tutor_hours, name="tutor_hours"),
        path('groups/', statistics.fetch_group_hours, name="group_hours"),
    ])),

    # from screen to db
    path('change_edt', views.edt_changes, name="edt_changes"),
    path('change_user_pref/<int:year>/<int:week>/<str:username>',
         views.user_preferences_changes,
         name="user_pref_changes"),
    path('change_course_pref/<int:year>/<int:week>/<str:train_prog>/<str:course_type>', views.course_preferences_changes, name="course_pref_changes"),
    path('change_room_pref/<int:year>/<int:week>/<str:room>',
         views.room_preferences_changes,
         name="room_pref_changes"),
    path('change_decale', views.decale_changes, name="decale_changes"),
    path('change_perfect_day/<str:username>',
         views.user_perfect_day_changes,
         name="user_perfect_day_changes"),
    path('change_user_notifications_pref/<str:username>',
         views.user_notifications_pref_changes,
         name="user_notifications_pref_changes"),
    path(r'change_room_pref_per_tutor/<str:tutor>',
         views.room_preferences_changes_per_tutor,
         name='room_pref_changes_per_tutor'),

    # predefined
    # ------------
]

# https://pypi.python.org/pypi/django-live-log
# https://github.com/abdullatheef/django_live_log

FlOpEDT/flopeditor/urls.py
# -*- coding: utf-8 -*-
"""
Python versions: Python 3.6

This file is part of the FlOpEDT/FlOpScheduler project.
Copyright (c) 2017
Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public
License along with this program. If not, see
<http://www.gnu.org/licenses/>.

You can be released from the requirements of the license by purchasing
a commercial license. Buying such a license is mandatory as soon as
you develop activities involving the FlOpEDT/FlOpScheduler software
without disclosing the source code of your own applications.


This module is used to declare the urls related to flop!EDITOR, an app used
to manage a department statistics for FlOpEDT.
"""

from django.urls import path
from . import views, crud

app_name = "flopeditor"

urlpatterns = [
    # directly reachable by users
    # ---------------------------
    path('', views.home, name='flopeditor-home'),
    path('flopeditor-help/', views.flopeditor_help, name='flopeditor-help'),
    path('<slug:department_abbrev>/', views.department_default,
         name='flopeditor-department-default'),
    path('<slug:department_abbrev>/salles', views.department_rooms,
         name='flopeditor-department-rooms'),
    path('<slug:department_abbrev>/intervenants', views.department_tutors,
         name='flopeditor-department-tutors'),
    path('<slug:department_abbrev>/categories-de-salles', views.department_room_types,
         name='flopeditor-department-room-types'),
    path('<slug:department_abbrev>/groupes-structuraux', views.department_student_structural_groups,
         name='flopeditor-department-student-structural-groups'),
    path('<slug:department_abbrev>/groupes-transversaux', views.department_student_transversal_groups,
         name='flopeditor-department-student-transversal-groups'),
    path('<slug:department_abbrev>/natures', views.department_student_group_types,
         name='flopeditor-department-student-group-types'),
    path('<slug:department_abbrev>/promos', views.department_training_programmes,
         name='flopeditor-department-training-programmes'),
    path('<slug:department_abbrev>/modules', views.department_modules,
         name='flopeditor-department-modules'),
    path('<slug:department_abbrev>/types-de-cours', views.department_course_types,
         name='flopeditor-department-course-types'),
    path('<slug:department_abbrev>/semestres', views.department_periods,
         name='flopeditor-department-periods'),

    path('<slug:department_abbrev>/parameters', views.department_parameters,
         name='flopeditor-department-parameters'),
    path('<slug:department_abbrev>/parameters/edit', views.department_parameters_edit,
         name='flopeditor-department-parameters-edit'),



    # exchanges with the db via django
    # --------------------------------
    path('ajax/create-department', views.ajax_create_department,
         name="flopeditor-ajax-create-department"),
    path('ajax/update-department', views.ajax_update_department,
         name="flopeditor-ajax-update-department"),
    path('ajax/parameters-edit/<slug:department_abbrev>', views.ajax_edit_parameters,
         name='flopeditor-ajax-edit-department-parameters'),
    path('ajax/update-profil', views.ajax_update_profil,
         name='flopeditor-ajax-update-profil'),

    # exchanges with the CRUD
    # --------------------------------
    path('<slug:department_abbrev>/crud/rooms', crud.crud_rooms,
         name='flopeditor-crud-rooms'),
    path('<slug:department_abbrev>/crud/tutors', crud.crud_tutors,
         name='flopeditor-crud-tutors'),
    path('<slug:department_abbrev>/crud/room_types', crud.crud_room_types,
         name='flopeditor-crud-room-types'),
    path('<slug:department_abbrev>/crud/group_type', crud.crud_student_group_type,
         name='flopeditor-crud-student-group-type'),
    path('<slug:department_abbrev>/crud/student_structural_group', crud.crud_student_structural_group,
         name='flopeditor-crud-student-structural-group'),
    path('<slug:department_abbrev>/crud/student_transversal_group', crud.crud_student_transversal_group,
         name='flopeditor-crud-student-transversal-group'),
    path('<slug:department_abbrev>/crud/modules', crud.crud_module,
         name='flopeditor-crud-modules'),
    path('<slug:department_abbrev>/crud/training_programmes', crud.crud_training_programmes,
         name='flopeditor-crud-training-programmes'),
    path('<slug:department_abbrev>/crud/courses', crud.crud_course,
         name='flopeditor-crud-courses'),
    path('<slug:department_abbrev>/crud/periods', crud.crud_periods,
         name='flopeditor-crud-periods'),

]

FlOpEDT/flopeditor/templates/flopeditor/modules.html
<!-- This file is part of the FlOpEDT/FlOpScheduler project.               -->
<!-- Copyright (c) 2017                                                    -->
<!-- Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.           -->
<!--                                                                       -->
<!-- This program is free software: you can redistribute it and/or modify  -->
<!-- it under the terms of the GNU Affero General Public License as        -->
<!-- published by the Free Software Foundation, either version 3 of the    -->
<!-- License, or (at your option) any later version.                       -->
<!--                                                                       -->
<!-- This program is distributed in the hope that it will be useful, but   -->
<!-- WITHOUT ANY WARRANTY; without even the implied warranty of            -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU      -->
<!-- Affero General Public License for more details.                       -->
<!--                                                                       -->
<!-- You should have received a copy of the GNU Affero General Public      -->
<!-- License along with this program. If not, see                          -->
<!-- <http://www.gnu.org/licenses/>.                                       -->
<!--                                                                       -->
<!-- You can be released from the requirements of the license by purchasing -->
<!-- a commercial license. Buying such a license is mandatory as soon as   -->
<!-- you develop activities involving the FlOpEDT/FlOpScheduler software   -->
<!-- without disclosing the source code of your own applications.          -->

{% extends "flopeditor/base_crud.html" %}
{% load static %} 
{% block nav-classes-modules %} active {% endblock %} 

{% block main-class %}container-fluid{% endblock %}

{% block card_header %}
<li class="nav-item">
  <a
    class="nav-link {% block card-nav-classes-modules %}active{% endblock %}"
    href="{% url 'flopeditor:flopeditor-department-modules' department_abbrev=department.abbrev %}"
  >
    Modules
  </a>
</li>
<li class="nav-item">
  <a
    class="nav-link {% block card-nav-classes-periods %}{% endblock %}"
    href="{% url 'flopeditor:flopeditor-department-periods' department_abbrev=department.abbrev %}"
  >
    Semestres
  </a>
</li>
{% endblock %} 

{% block crud_js_url %}{% url 'flopeditor:flopeditor-crud-modules' department_abbrev=department.abbrev %}{% endblock %}

FlOpEDT/flopeditor/templates/flopeditor/periods.html
<!-- This file is part of the FlOpEDT/FlOpScheduler project.               -->
<!-- Copyright (c) 2017                                                    -->
<!-- Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.           -->
<!--                                                                       -->
<!-- This program is free software: you can redistribute it and/or modify  -->
<!-- it under the terms of the GNU Affero General Public License as        -->
<!-- published by the Free Software Foundation, either version 3 of the    -->
<!-- License, or (at your option) any later version.                       -->
<!--                                                                       -->
<!-- This program is distributed in the hope that it will be useful, but   -->
<!-- WITHOUT ANY WARRANTY; without even the implied warranty of            -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU      -->
<!-- Affero General Public License for more details.                       -->
<!--                                                                       -->
<!-- You should have received a copy of the GNU Affero General Public      -->
<!-- License along with this program. If not, see                          -->
<!-- <http://www.gnu.org/licenses/>.                                       -->
<!--                                                                       -->
<!-- You can be released from the requirements of the license by purchasing -->
<!-- a commercial license. Buying such a license is mandatory as soon as   -->
<!-- you develop activities involving the FlOpEDT/FlOpScheduler software   -->
<!-- without disclosing the source code of your own applications.          -->

{% extends "flopeditor/modules.html" %}
{% load static %}

{% block card-nav-classes-modules %}{% endblock %}
{% block card-nav-classes-periods %}active{% endblock %}


{% block crud_js_url %}{% url 'flopeditor:flopeditor-crud-periods' department_abbrev=department.abbrev %}{% endblock %}

FlOpEDT/flopeditor/templates/flopeditor/rooms.html
<!-- This file is part of the FlOpEDT/FlOpScheduler project.               -->
<!-- Copyright (c) 2017                                                    -->
<!-- Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.           -->
<!--                                                                       -->
<!-- This program is free software: you can redistribute it and/or modify  -->
<!-- it under the terms of the GNU Affero General Public License as        -->
<!-- published by the Free Software Foundation, either version 3 of the    -->
<!-- License, or (at your option) any later version.                       -->
<!--                                                                       -->
<!-- This program is distributed in the hope that it will be useful, but   -->
<!-- WITHOUT ANY WARRANTY; without even the implied warranty of            -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU      -->
<!-- Affero General Public License for more details.                       -->
<!--                                                                       -->
<!-- You should have received a copy of the GNU Affero General Public      -->
<!-- License along with this program. If not, see                          -->
<!-- <http://www.gnu.org/licenses/>.                                       -->
<!--                                                                       -->
<!-- You can be released from the requirements of the license by purchasing -->
<!-- a commercial license. Buying such a license is mandatory as soon as   -->
<!-- you develop activities involving the FlOpEDT/FlOpScheduler software   -->
<!-- without disclosing the source code of your own applications.          -->

{% extends "flopeditor/base_crud.html" %}
{% load static %}
{% block nav-classes-rooms %} active {% endblock %}

{% block card_header %}
    <li class="nav-item">
        <a  class="nav-link {% block card-nav-classes-rooms %}active{% endblock %}"
            href="{% url 'flopeditor:flopeditor-department-rooms' department_abbrev=department.abbrev %}">
            Salles
        </a>
    </li>
      <li class="nav-item">
          <a  class="nav-link {% block card-nav-classes-room-types %}{% endblock %}"
              href="{% url 'flopeditor:flopeditor-department-room-types' department_abbrev=department.abbrev %}">
              Catégories de salles
          </a>
      </li>
{% endblock %}


{% block crud_js_url %}{% url 'flopeditor:flopeditor-crud-rooms' department_abbrev=department.abbrev %}{% endblock %}
<!-- {---% url 'flopeditor:flopeditor-crud-xxxxx' department_abbrev=department.abbrev %} -->

FlOpEDT/flopeditor/templates/flopeditor/student_group_types.html
<!-- This file is part of the FlOpEDT/FlOpScheduler project.               -->
<!-- Copyright (c) 2017                                                    -->
<!-- Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.           -->
<!--                                                                       -->
<!-- This program is free software: you can redistribute it and/or modify  -->
<!-- it under the terms of the GNU Affero General Public License as        -->
<!-- published by the Free Software Foundation, either version 3 of the    -->
<!-- License, or (at your option) any later version.                       -->
<!--                                                                       -->
<!-- This program is distributed in the hope that it will be useful, but   -->
<!-- WITHOUT ANY WARRANTY; without even the implied warranty of            -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU      -->
<!-- Affero General Public License for more details.                       -->
<!--                                                                       -->
<!-- You should have received a copy of the GNU Affero General Public      -->
<!-- License along with this program. If not, see                          -->
<!-- <http://www.gnu.org/licenses/>.                                       -->
<!--                                                                       -->
<!-- You can be released from the requirements of the license by purchasing -->
<!-- a commercial license. Buying such a license is mandatory as soon as   -->
<!-- you develop activities involving the FlOpEDT/FlOpScheduler software   -->
<!-- without disclosing the source code of your own applications.          -->

{% extends "flopeditor/base_crud.html" %}
{% load static %}
{% block nav-classes-groups %} active {% endblock %}

{% block card_header %}
    <li class="nav-item">
        <a  class="nav-link {% block card-nav-classes-training-programmes %}{% endblock %}"
            href="{% url 'flopeditor:flopeditor-department-training-programmes' department_abbrev=department.abbrev %}">
            Promos
        </a>
    </li>
    <li class="nav-item">
        <a  class="nav-link {% block card-nav-classes-student-group-types %}active{% endblock %}"
            href="{% url 'flopeditor:flopeditor-department-student-group-types' department_abbrev=department.abbrev %}">
            Natures de groupes
        </a>
    </li>
    <li class="nav-item">
        <a  class="nav-link {% block card-nav-classes-student-structural-groups %}{% endblock %}"
            href="{% url 'flopeditor:flopeditor-department-student-structural-groups' department_abbrev=department.abbrev %}">
            Groupes structuraux
        </a>
    </li>
    <li class="nav-item">
        <a  class="nav-link {% block card-nav-classes-student-transversal-groups %}{% endblock %}"
            href="{% url 'flopeditor:flopeditor-department-student-transversal-groups' department_abbrev=department.abbrev %}">
            Groupes transversaux
        </a>
    </li>
{% endblock %}

{% block crud_js_url %}{% url 'flopeditor:flopeditor-crud-student-group-type' department_abbrev=department.abbrev %}{% endblock %}